"""add new fields to User

Revision ID: cc7d53a50be0
Revises: c92501b80749
Create Date: 2022-11-10 23:47:04.628919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7d53a50be0'
down_revision = 'c92501b80749'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chats', ['chat_id'])
    op.add_column('users', sa.Column('can_send_messages', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_send_media_messages', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_send_other_messages', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_send_polls', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_add_web_page_previews', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_invite_users', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_pin_messages', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_change_info', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'can_change_info')
    op.drop_column('users', 'can_pin_messages')
    op.drop_column('users', 'can_invite_users')
    op.drop_column('users', 'can_add_web_page_previews')
    op.drop_column('users', 'can_send_polls')
    op.drop_column('users', 'can_send_other_messages')
    op.drop_column('users', 'can_send_media_messages')
    op.drop_column('users', 'can_send_messages')
    op.drop_constraint(None, 'chats', type_='unique')
    # ### end Alembic commands ###
