"""remove fields from User

Revision ID: d865c8aeed2e
Revises: cc7d53a50be0
Create Date: 2022-11-11 05:05:16.799066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd865c8aeed2e'
down_revision = 'cc7d53a50be0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_send_voice_messages', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_send_video_messages', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('can_send_stickers', sa.Boolean(), nullable=True))
    op.drop_column('users', 'can_change_info')
    op.drop_column('users', 'can_pin_messages')
    op.drop_column('users', 'can_send_media_messages')
    op.drop_column('users', 'can_send_other_messages')
    op.drop_column('users', 'can_send_polls')
    op.drop_column('users', 'can_invite_users')
    op.drop_column('users', 'can_send_messages')
    op.drop_column('users', 'can_add_web_page_previews')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_add_web_page_previews', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('can_send_messages', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('can_invite_users', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('can_send_polls', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('can_send_other_messages', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('can_send_media_messages', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('can_pin_messages', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('can_change_info', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'can_send_stickers')
    op.drop_column('users', 'can_send_video_messages')
    op.drop_column('users', 'can_send_voice_messages')
    # ### end Alembic commands ###
